#This is the makefile used by the make utility to compile the Final Project
Final-Project:
	g++ ./src/turing50.cpp -o ./bin/turing50 -std=gnu++11
	g++ ./src/evolve50.cpp -o ./bin/evolve50 -std=gnu++11
