CREATE DATABASE IF NOT EXISTS webtech;

USE webtech;

CREATE TABLE IF NOT EXISTS groups(
userid INT(10) NOT NULL UNIQUE PRIMARY KEY ,
usertype VARCHAR(65) NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
userid INT(10) NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY ,
username VARCHAR(65) NOT UNIQUE NULL ,
pass_word VARCHAR(767) NOT NULL,
FOREIGN KEY fk_userid(userid)
REFERENCES groups(userid)
ON UPDATE CASCADE
ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS admins(
userid INT(10) NOT NULL UNIQUE PRIMARY KEY ,
username VARCHAR(65) NOT NULL UNIQUE,
pass_word VARCHAR(767) NOT NULL,
FOREIGN KEY fk_userid(userid)
REFERENCES groups(userid)
ON UPDATE RESTRICT
ON DELETE RESTRICT
);


-- to be added to php later
CREATE TABLE IF NOT EXISTS $userid(
stocksymbol VARCHAR(10) NOT NULL UNIQUE PRIMARY KEY,
stockcount INT(30) NOT NULL,
FOREIGN KEY fk_userid(userid)
REFERENCES users(userid)
ON UPDATE CASCADE
ON DELETE CASCADE
);
