CREATE DATABASE IF NOT EXISTS webtech;

USE webtech;

CREATE TABLE IF NOT EXISTS groups(
userid INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
usertype VARCHAR(65) NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
userid INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
username VARCHAR(65) NOT NULL ,
pass_word VARCHAR(767) NOT NULL,
FOREIGN KEY fk_userid(userid)
REFERENCES groups(userid)
ON UPDATE CASCADE
ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS admins(
userid INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
username VARCHAR(65) NOT NULL ,
pass_word VARCHAR(767) NOT NULL,
FOREIGN KEY fk_userid(userid)
REFERENCES groups(userid)
ON UPDATE CASCADE
ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS shares(
userid INT(10) NOT NULL AUTO_INCREMENT,
stocksymbol VARCHAR(10) NOT NULL,
stockcount INT(30) NOT NULL,
PRIMARY KEY (userid,stocksymbol),
FOREIGN KEY fk_userid(userid)
REFERENCES users(userid)
ON UPDATE CASCADE
ON DELETE CASCADE
);
