#!/bin/bash

# Copyright 2017 Aly Shmahell
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http:#www.apache.org/licenses/LICENSE-2.0 . Unless
# required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#
# Author: Aly Shmahell

(cd G0Bot && make 2>&1 > /dev/null && make clean 2>&1 > /dev/null)
java -jar PlanetWars-viz/PlayGame.jar 2>&1 "maps/map92.txt" 10000 10000 log.txt "java -jar 3rdPartyBots/Genebot.jar" "java -jar ./G0Bot/G0Bot.jar" 2>&1 >/dev/null | echo $(tail -1) > winner.txt
