#!/bin/bash

(cd 0SumBot && make && make clean)
(cd PlanetWars-viz && make && make clean)
java -jar PlanetWars-viz/PlayGame.jar "maps/map100.txt" 1000 1000 log.txt "java -jar 3rdPartyBots/Genebot.jar" "java -jar
./0SumBot/0SumBot.jar" | java -jar PlanetWars-viz/ShowGame.jar
