#!/usr/bin/env python3

import os
import hashlib
import argparse

if __name__ == '__main__':
    parser  = argparse.ArgumentParser()
    parser.add_argument("-u", type=str, help="mysql username")
    parser.add_argument("-db", type=str, help="mysql database")
    parser.add_argument("-admin", type=str, help="new admin name")
    parser.add_argument("-password", type=str, help="new admin password")
    args = parser .parse_args()
    print(f"sudo mysql -u {args.u} -p -e \"use {args.db}; INSERT INTO groups VALUES ('{args.admin}', 'admin');\"")
    os.system(f"sudo mysql -u {args.u} -p -e \"use {args.db}; INSERT INTO groups VALUES ('{args.admin}', 'admin');\"")
    password = hashlib.sha512(f"{args.password}".encode("utf8")).hexdigest()
    os.system(f"sudo mysql -u {args.u} -p -e \"use {args.db}; INSERT INTO users VALUES ('{args.admin}', '{password}');\"")