#!/usr/bin/env python3


import os
import argparse

if __name__ == '__main__':
    parser  = argparse.ArgumentParser()
    parser.add_argument("-host", type=str, help="configure host")
    parser.add_argument("-port", type=str, help="configure port")
    args = parser .parse_args()
    os.system(f"cd src/site && php -S {args.host}:{args.port}")